-- Create the database
CREATE DATABASE LibraryDB;
USE LibraryDB;

-- Create the tables in proper order
CREATE TABLE LIB_ACCOUNT_TYPE (
    AccountTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE LIB_ACCOUNT (
    AccountID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State CHAR(5) NOT NULL,
    Zip CHAR(5) NOT NULL,
    StartDate DATE NOT NULL,
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    AccountTypeID TINYINT NOT NULL,
    FOREIGN KEY (AccountTypeID) REFERENCES LIB_ACCOUNT_TYPE(AccountTypeID)
);

CREATE TABLE LIB_CLASS (
    ClassID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    DurationMins TINYINT,
    ImagePath VARCHAR(255)
);

CREATE TABLE LIB_EVENT (
    EventID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    ImagePath VARCHAR(255)
);

CREATE TABLE LIB_ROOM (
    RoomID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Capacity TINYINT
);

CREATE TABLE LIB_CLASS_SCHEDULE (
    ScheduleSlotID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    ClassID TINYINT,
    RoomID TINYINT,
    FOREIGN KEY (ClassID) REFERENCES LIB_CLASS(ClassID),
    FOREIGN KEY (RoomID) REFERENCES LIB_ROOM(RoomID)
);

CREATE TABLE LIB_EVENT_SCHEDULE (
    ScheduleSlotID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,
    Time TIME NOT NULL,
    EventID TINYINT,
    RoomID TINYINT,
    FOREIGN KEY (EventID) REFERENCES LIB_EVENT(EventID),
    FOREIGN KEY (RoomID) REFERENCES LIB_ROOM(RoomID)
);

CREATE TABLE LIB_CLASS_REGISTRATION (
    ScheduleSlotID INT,
    AccountID INT,
    PRIMARY KEY (ScheduleSlotID, AccountID),
    FOREIGN KEY (ScheduleSlotID) REFERENCES LIB_CLASS_SCHEDULE(ScheduleSlotID),
    FOREIGN KEY (AccountID) REFERENCES LIB_ACCOUNT(AccountID)
);

CREATE TABLE LIB_INSTRUCTOR (
    InstructorID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Gender CHAR(1),
    Bio TEXT,
    ImagePath VARCHAR(255)
);

CREATE TABLE LIB_CLASS_INSTRUCTOR (
    ClassID TINYINT,
    InstructorID TINYINT,
    PRIMARY KEY (ClassID, InstructorID),
    FOREIGN KEY (ClassID) REFERENCES LIB_CLASS(ClassID),
    FOREIGN KEY (InstructorID) REFERENCES LIB_INSTRUCTOR(InstructorID)
);

CREATE TABLE LIB_CHECKOUT (
    CheckoutID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AccountID INT NOT NULL,
    CheckoutDate DATE NOT NULL,
    DueDate DATE NOT NULL, -- Updated to NOT NULL
    ReturnDate DATE,
    FOREIGN KEY (AccountID) REFERENCES LIB_ACCOUNT(AccountID)
);

CREATE TABLE LIB_FEE_TYPE (
    FeeTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_FEES (
    CheckoutID BIGINT,
    AccountID INT,
    FeeTypeID TINYINT,
    Amount INT,
    PaidDate DATE,
    PRIMARY KEY (CheckoutID, FeeTypeID),
    FOREIGN KEY (CheckoutID) REFERENCES LIB_CHECKOUT(CheckoutID),
    FOREIGN KEY (AccountID) REFERENCES LIB_ACCOUNT(AccountID),
    FOREIGN KEY (FeeTypeID) REFERENCES LIB_FEE_TYPE(FeeTypeID)
);

CREATE TABLE LIB_ITEM_TYPE (
    ItemTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_MEDIA_TYPE (
    MediaTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_GENRE (
    GenreID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_PUBLISHER_TYPE (
    PublisherTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_PUBLISHER (
    PublisherID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    PublisherTypeID TINYINT, 
    FOREIGN KEY (PublisherTypeID) REFERENCES LIB_PUBLISHER_TYPE(PublisherTypeID)
);

CREATE TABLE LIB_CREATOR_TYPE (
    CreatorTypeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE LIB_CREATOR (
    CreatorID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Gender CHAR(1),
    DateBorn DATE,
    DateDied DATE,
    Bio TEXT,
    ImagePath VARCHAR(255),
    CreatorTypeID TINYINT,
    FOREIGN KEY (CreatorTypeID) REFERENCES LIB_CREATOR_TYPE(CreatorTypeID)
);

CREATE TABLE LIB_ITEM (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    Isbn VARCHAR(13) NOT NULL, 
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Year SMALLINT,
    IssueNumber TINYINT,
    LibCopies TINYINT,
    ImagePath VARCHAR(255), 
    LibLocation VARCHAR(50), 
    ItemTypeID TINYINT,
    MediaTypeID TINYINT,
    GenreID TINYINT,
    FOREIGN KEY (ItemTypeID) REFERENCES LIB_ITEM_TYPE(ItemTypeID),
    FOREIGN KEY (MediaTypeID) REFERENCES LIB_MEDIA_TYPE(MediaTypeID),
    FOREIGN KEY (GenreID) REFERENCES LIB_GENRE(GenreID)
);

CREATE TABLE LIB_ITEM_PUBLISHER (
    ItemID INT NOT NULL, 
    PublisherID TINYINT NOT NULL, 
    PRIMARY KEY (ItemID, PublisherID), 
    FOREIGN KEY (ItemID) REFERENCES LIB_ITEM(ItemID),
    FOREIGN KEY (PublisherID) REFERENCES LIB_PUBLISHER(PublisherID)
);

CREATE TABLE LIB_ITEM_CREATOR (
    ItemID INT,
    CreatorID INT,
    PRIMARY KEY (ItemID, CreatorID),
    FOREIGN KEY (ItemID) REFERENCES LIB_ITEM(ItemID),
    FOREIGN KEY (CreatorID) REFERENCES LIB_CREATOR(CreatorID)
);

CREATE TABLE LIB_CHECKOUT_ITEM (
    CheckoutID BIGINT,
    ItemID INT,
    PRIMARY KEY (CheckoutID, ItemID),
    FOREIGN KEY (CheckoutID) REFERENCES LIB_CHECKOUT(CheckoutID),
    FOREIGN KEY (ItemID) REFERENCES LIB_ITEM(ItemID)
);